controller_manager:
  ros__parameters:
    update_rate: 10 # Hz

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    # gripper_controller:
    #   type: forward_command_controller/ForwardCommandController

    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    joints:
      - bases_joint
      - base_arm1_joint
      - arm1_arm2_joint
      - arm2_arm3_joint
      - arm3_wrist_joint

    command_interfaces:
      - position

    state_interfaces:
      - position

    open_loop_control: true
    allow_integration_in_goal_trajectories: true

gripper_controller:
  ros__parameters:
    joints:
      - wrist_gripl_joint
    # interface_name: position

    command_interfaces:
      - position

    state_interfaces:
      - position

    open_loop_control: true
    allow_integration_in_goal_trajectories: true
